### ISSUE TITLE
Error while executing code

### ISSUE THREAD

**Issue by saikumarkethi** [sdjsngs/Re-implement-Memorizing-Normality-to-Detect-Anomaly#2]
Traceback (most recent call last):
  File "/content/Re-implement-Memorizing-Normality-to-Detect-Anomaly/train.py", line 6, in <module>
    from net.utils.parser import load_config,parse_args
  File "/content/Re-implement-Memorizing-Normality-to-Detect-Anomaly/net/utils/parser.py", line 6, in <module>
    from net.config.defaults import get_cfg
  File "/content/Re-implement-Memorizing-Normality-to-Detect-Anomaly/net/config/defaults.py", line 4, in <module>
    from fvcore.common.config import CfgNode
ModuleNotFoundError: No module named 'fvcore'

**Comment by sdjsngs** [comment]
fvcore can be installed in fvcore: pip install 'git+https://github.com/facebookresearch/fvcore'
